modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/Tick-Accelerator-Block/issues/new/choose"
[[mods]]
modId="tickaccelerator"
version="${file.jarVersion}"
displayName="Tick Accelerator Block"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tick-accelerator-block"
logoFile="examplemod.png"
credits="Thanks for downloading this mod."
authors="YTrollman"
description="This mod adds a Tick Accelerator Block."

[[dependencies.tickaccelerator]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tickaccelerator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"